import secrets
from flask import Flask, render_template, request, redirect, url_for
import os, base64

app = Flask(__name__)

# Set the secret key to a random value (generated by secrets.token_hex())
app.secret_key = secrets.token_hex(128)

# Define the route for the homepage
@app.route('/')
def home():
    nickname, command, data = base64.b64encode(b"admin").decode(), "proxy", base64.b64encode(b"https://cgsg.pml30.ru/").decode()
    return render_template('home.html', nickname=nickname, command=command, data=data)

@app.route('/home', methods=['GET'])
def smth():
    nickname, command, data = base64.b64encode("admin"), "proxy", base64.b64encode("https://cgsg.pml30.ru/")

if __name__ == '__main__':
    app.run(debug=False)
